### ISSUE TITLE
Assertions are not generated for package protected classes

### ISSUE THREAD

**Issue by jgerken** [joel-costigliola/assertj-assertions-generator-maven-plugin#46]
When I update my maven build to use version 2.1.0 of the `assertj-assertions-generator-maven-plugin` the build fails because some assertions were not generated. All affected classes are package protected classes, e.g.

```java
final class MyClass {
  // contents of the class omitted
}
```

The assertion reports lists the affected classes in this section:

```
No custom assertions files generated for the following input classes as they were not found:
```

Using version 2.0.0 the assertions for the package protected classes are generated.

Thus, I cannot update to version 2.1.0 because my tests will no longer compile. Increasing the visibility of the classes to `public` just be make the generator plugin work is not an option.

**Comment by joel-costigliola** [comment]
Thanks for reporting this !

**Comment by remibantos** [comment]
Any update on this issue? I have noticed that there is not much activity now in this project. Is it still maintained?

**Comment by joel-costigliola** [comment]
It's not dead but with my limited spare time, I haven't had the chance to work on it.
It is not clear if I will but I'd like to ideally.

**Comment by joel-costigliola** [comment]
If someone contribute I'm happy to release a new version though.

**Comment by remibantos** [comment]
Hi @joel-costigliola ,
This bugs has been caused by this [assertj-assertions-generator](https://github.com/joel-costigliola/assertj-assertions-generator) [commit](https://github.com/joel-costigliola/assertj-assertions-generator/commit/06839b092a12ef9545cdfb3bd1c019492fd79881) (since 2.1.0).

I could eventually PR the related change revert in ClassUtil, however your commit comment is very explicit...

**Comment by joel-costigliola** [comment]
I believe the right thing to do is to add an option in the configuration to allow generating package private classes. This should be done in the [generator](https://github.com/joel-costigliola/assertj-assertions-generator) and exposed to this plugin.

I don't have the time to work on this but I'm happy to accept PR.

**Comment by remibantos** [comment]
Ok, will do that, thanks

**Comment by remibantos** [comment]
Hi @joel-costigliola,
Did the PR. I have noticed that there is not travis-ci configuration for this project.
This PR depends on [this one ](https://github.com/joel-costigliola/assertj-assertions-generator/pull/130) which had failed due to a permission issue during sonar-maven-plugin execution in Travis. (Looks like the [sonar.login](https://github.com/joel-costigliola/assertj-assertions-generator/blob/master/.travis.yml) or configuration is not valid anymore.

**Comment by remibantos** [comment]
@joel-costigliola For information, I have just noticed that the package private assertions classes are also referenced in the entry points assertions classes, like _BddAssertions_...
So if this new _includePackagePrivateClasses_ option is enabled, either:
- the _entryPointClassPackage_ configuration should match the package which contains  assertions for package private classes
- or the entry points assertions classes generation should be disabled

Ideally, package private classes should not be referenced in entry points classes
